import './globals.css'
import Navbar from '@/components/Navbar'
import Providers from './Providers'

export const metadata = {
  title: "mongodb-nextjs-crud",
  description: "Generated by @daytascientist"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.js. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body>
        <Navbar />
        <main className='container mx-auto px-5 mt-4'>
          <Providers>
            {children}
          </Providers>
        </main>
      </body>
    </html>
  )
}
